### PR TITLE
Update decontextualize.scm

### PR DESCRIPTION
**Pull request by TeamSPoon**
Added missing bracket

### CODE REVIEW

**Comment by linas** [comment]
Merged because the patch is obviously correct (even though this is @ngeiswei bailiwick) 

Unit tests are failing because of some crazy python bug that showed up a month ago. I would like to think its totally unrelated, but ... I messed with docker containers about a month ago; maybe I broke something?  I'm pretty clueless about docker and circleci; if anyone has any idea please say something.

**Comment by ngeiswei** [comment]
Thanks for your fix @TeamSPoon, note however that rules under the `wip` folder are unmaintained, possibly even abandoned.

**Comment by linas** [comment]
"wip" == work in progress.  I've been using "attic" as a directory name for code that is obsolete, but which I don't want to delete (yet).

**Comment by ngeiswei** [comment]
The idea is to progressively fix the rules in `wip` and move them in non-wip folders, but many of them are obsolete.  Maybe I should split it into `wip` and `attic`, or do some exhaustive clean-up.

**Pull request merged**
